
name: Build and deploy Angular app to an Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        # pull_request:
        #   branches:
        #     - master

env:
  AZURE_WEBAPP_NAME: my-app-name   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.x'                # set this to the node version to use

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: "npm"
        cache-dependency-path: package-lock.json
        
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
    
    - name: Zip artifact for deployment
      run: |
        cd dist
        zip release.zip ./* -r

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: ./dist/release.zip

  ReuseableMatrixJobForDeployment:
    needs: build
    strategy:
      fail-fast: true
      matrix:
        target: [Development, Production ]
    uses: ./.github/workflows/deployment.yml
    with:
      target-env: ${{ matrix.target }}
    secrets: inherit


  # deployDev:
  #   name: Deploy to Dev
  #   permissions:
  #     contents: none
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: "Development"
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: node-app

  #     - name: unzip artifact for deployment
  #       run: unzip release.zip

  #     - name: "Deploy to Azure WebApp"
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: ${{ secrets.AZURE_WEBAPP_SERVICE_NAME }}
  #         slot-name: "production"
  #         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  
  # deployProd:
  #   name: Deploy to Production
  #   permissions:
  #     contents: none
  #   runs-on: ubuntu-latest
  #   needs: deployDev
  #   environment:
  #     name: "Production"
  #     url: ${{ steps.deploy-to-webapp-prod.outputs.webapp-url }}

  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: node-app

  #     - name: unzip artifact for deployment
  #       run: unzip release.zip

  #     - name: "Deploy to Azure WebApp"
  #       id: deploy-to-webapp-prod
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: ${{ secrets.AZURE_WEBAPP_SERVICE_NAME_PROD }}
  #         slot-name: "production"
  #         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD }}
  #         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}